# TTS-prepared script, trimmed to fit under 3:00.
# (slide_index, caption_text, tts_text, pause_after_seconds)
SEGMENTS = [
 (1,"This child has Mosaic Variegated Aneuploidy type 1.",
    "This child has Mosaic Variegated Aneuploidy, type one.",0.3),
 (1,"Two variants in BUB1B.",
    "Two variants in the gene, bub one bee.",0.25),
 (1,"A stop at codon 737 — ClinVar already calls it pathogenic for this exact disease.",
    "A stop at codon seven thirty seven, that ClinVar already calls pathogenic for this exact disease.",0.3),
 (1,"And a novel missense at asparagine 1002 — one allele in 1.5 million — in the pseudokinase domain.",
    "And a novel missense at asparagine one thousand and two. One allele in one and a half million. In the pseudokinase domain.",0.45),
 (1,"It ranked first genome-wide with no gene-panel prior, and we confirmed it from the raw reads.",
    "It ranked first genome wide with no gene panel prior. And we confirmed it from the raw reads, without trusting the variant caller.",0.6),

 (2,"The truncating allele makes no protein. Nonsense-mediated decay removes it.",
    "The truncating allele makes no protein. Nonsense mediated decay removes it.",0.3),
 (2,"So everything this child has comes from the other copy.",
    "So everything this child has comes from the other copy.",0.45),
 (2,"And the work on that class of mutation is unusually clear.",
    "And the work on that class of mutation is unusually clear.",0.3),
 (2,"These are not broken proteins. They are scarce proteins.",
    "These are not broken proteins. They are scarce proteins.",0.35),
 (2,"Same messenger RNA. Five to ten times less protein. Twice the turnover.",
    "Same messenger RNA. Five to ten times less protein. Twice the turnover.",0.3),
 (2,"Force them back to normal levels and the checkpoint works perfectly again.",
    "Force them back to normal levels, and the checkpoint works perfectly again.",0.5),
 (2,"This is not a disease of a protein that doesn't function. It's one that doesn't last.",
    "This is not a disease of a protein that doesn't function. It's a disease of a protein that doesn't last.",0.7),

 (3,"That reframes the target — and it lets us put a number on it.",
    "That reframes the target. And it lets us put a number on it.",0.45),
 (3,"The dose-response for BUBR1 is a switch, not a slope.",
    "The dose response for bub arr one is a switch, not a slope.",0.35),
 (3,"Six percent of normal, and most cells missegregate.",
    "Six percent of normal, and most cells missegregate.",0.3),
 (3,"Thirteen percent, and segregation is essentially fine.",
    "Thirteen percent, and segregation is essentially fine.",0.5),
 (3,"This child sits between five and ten percent. Right on the edge.",
    "This child sits between five and ten percent. Right on the edge.",0.8),
 (3,"To get him over the line, raise one destabilised protein by 1.3 to 2.6 fold.",
    "To get him over the line, you raise one destabilised protein by one point three, to two point six fold.",0.45),
 (3,"Not restore it. Not replace the gene. Roughly double it.",
    "Not restore it. Not replace the gene. Roughly double it.",0.55),
 (3,"A drug-scale target — and a bar every candidate must clear, set before we run anything.",
    "That is a drug scale target. And it gives every candidate a bar to clear, set before we run anything.",0.7),

 (4,"Now the part we think matters most.",
    "Now, the part we think matters most.",0.45),
 (4,"Every published aneuploidy-selective drug kills aneuploid cells preferentially.",
    "Every published aneuploidy selective drug kills aneuploid cells preferentially.",0.3),
 (4,"In a tumour inside a healthy patient, that difference is the whole therapy.",
    "In a tumour inside a healthy patient, that difference is the whole therapy.",0.5),
 (4,"But here, the patient is the aneuploid organism. Brain, muscle, marrow all carry it.",
    "But here, the patient is the aneuploid organism. Brain, muscle and marrow all carry it.",0.4),
 (4,"The therapeutic index isn't narrow. It's inverted.",
    "The therapeutic index isn't narrow. It's inverted.",0.7),
 (4,"So that literature is a list of things to avoid here, not a list of leads.",
    "So that literature is a list of things to avoid here, not a list of leads.",0.45),
 (4,"And HSP90 inhibitors are the worst of them for this child.",
    "And H S P ninety inhibitors are the worst of them, for this child.",0.3),
 (4,"His surviving allele is the one that depends on HSP90 to fold.",
    "His surviving allele is the one that depends on H S P ninety to fold.",0.3),
 (4,"You'd be stripping away the only working copy he has.",
    "You would be stripping away the only working copy he has.",0.6),
 (4,"The same logic rules out senolytics and growth hormone.",
    "The same logic rules out senolytics, and growth hormone.",0.3),
 (4,"And it raises a question nobody has asked about his current treatment.",
    "And it raises a question nobody has asked about his current treatment.",0.7),

 (5,"He has rhabdomyosarcoma. Rhabdomyosarcoma is treated with vincristine.",
    "He has rhabdomyosarcoma. And rhabdomyosarcoma is treated with vincristine.",0.6),
 (5,"Vinca alkaloids don't kill by damaging microtubules.",
    "Vinca alkaloids don't kill by damaging microtubules.",0.3),
 (5,"They kill by holding a cell in mitotic arrest, maintained by the spindle checkpoint.",
    "They kill by holding a cell in mitotic arrest, maintained by the spindle checkpoint.",0.45),
 (5,"His checkpoint is the disease.",
    "His checkpoint is the disease.",0.55),
 (5,"His cells slip out of arrest in about an hour, where normal cells hold indefinitely.",
    "His cells slip out of arrest in about an hour, where normal cells hold indefinitely.",0.5),
 (5,"So the prediction is they don't die. They escape, carrying a wrecked genome.",
    "So the prediction is they don't die. They escape, carrying a wrecked genome.",0.45),
 (5,"In a child with a 37% lifetime cancer risk, that's a serious question.",
    "In a child with a thirty seven percent lifetime cancer risk, that is a serious question.",0.45),
 (5,"One plate of patient cells answers it.",
    "One plate of patient cells answers it.",0.8),

 (6,"One cell system. Three readouts. One threshold, set in advance.",
    "One cell system. Three readouts. One threshold, set in advance.",0.35),
 (6,"Protein up 1.3 fold, or it isn't a hit.",
    "Protein up one point three fold, or it isn't a hit.",0.6),
 (6,"Everything is public, and it runs on one CPU. Thank you.",
    "Everything is public, and it runs on one C P U. Thank you.",0.45),
]
